import { useEffect, useState, useCallback } from "react";
import type { Level, QuestionFamily } from "@/data/seed";
import type { BuilderHandoffItem } from "@/lib/builderHandoff";

/** A single paragraph card produced by the Paragraph Engine.
 *  Stored on the plan as an ordered array; persisted as JSONB on
 *  saved_essay_plans.paragraph_cards. */
export interface ParagraphCard {
  id: string;
  title: string;
  claim: string;
  comparative_direction: string;
  /** Quote ids selected for Hard Times. */
  evidence_ht_ids: string[];
  /** Quote ids selected for Atonement. */
  evidence_at_ids: string[];
  /** Optional comparative quote ids. */
  evidence_cmp_ids: string[];
  method_focus: string;
  context_anchor: string;
  ao5_prompt: string;
  notes: string;
  /** Source paragraph_job id when seeded from one. */
  seed_job_id?: string;
  /** True for cards generated by the engine that the student hasn't yet
   *  touched. Cleared on the first meaningful edit (claim / evidence /
   *  method / context / AO5 / notes / title / comparative direction). Used
   *  purely as a UI hint ("Draft lane"); persistence is unaffected. */
  draft?: boolean;
}

export interface EssayPlan {
  id: string;
  updated_at: number;
  question_id?: string;
  family?: QuestionFamily;
  route_id?: string;
  thesis_level: Level;
  thesis_id?: string;
  selected_quote_ids: string[];
  ao5_enabled: boolean;
  selected_ao5_ids: string[];
  notes?: string;
  paragraph_cards?: ParagraphCard[];
  /** Durable current-plan owner for Builder intake notes imported from Explore. */
  builder_handoffs?: BuilderHandoffItem[];
}

export interface TimedSession {
  id: string;
  plan_id: string;
  mode_id: string;
  created_at: number;
  response: string;
  reflection: Record<string, boolean>;
  first_failure: string;
}

const KEY_CURRENT = "c2p.currentPlan.v1";
const KEY_SAVED = "c2p.savedPlans.v1";
const KEY_LAST_SESSION = "c2p.lastSession.v1";

export const emptyPlan = (): EssayPlan => ({
  id: `plan_${Date.now()}`,
  updated_at: Date.now(),
  thesis_level: "strong",
  selected_quote_ids: [],
  ao5_enabled: false,
  selected_ao5_ids: [],
  paragraph_cards: [],
  builder_handoffs: [],
});

function dedupe<T>(items: T[] | undefined): T[] {
  return Array.from(new Set(items ?? []));
}

export function normalizeEssayPlan(plan?: Partial<EssayPlan> | null): EssayPlan {
  const base = emptyPlan();
  if (!plan) return base;

  return {
    ...base,
    ...plan,
    id: typeof plan.id === "string" && plan.id.length > 0 ? plan.id : base.id,
    updated_at: typeof plan.updated_at === "number" ? plan.updated_at : base.updated_at,
    thesis_level: plan.thesis_level ?? base.thesis_level,
    selected_quote_ids: dedupe(plan.selected_quote_ids),
    selected_ao5_ids: dedupe(plan.selected_ao5_ids).slice(0, 3),
    paragraph_cards: Array.isArray(plan.paragraph_cards) ? plan.paragraph_cards : [],
    builder_handoffs: Array.isArray(plan.builder_handoffs) ? plan.builder_handoffs : [],
  };
}

/** A plan is "meaningful" if the student has progressed past picking a family. */
export function hasMeaningfulPlan(plan?: EssayPlan | null): boolean {
  if (!plan) return false;
  return Boolean(plan.question_id && plan.route_id);
}

function read<T>(k: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(k);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

export function useCurrentPlan() {
  const [plan, setPlan] = useState<EssayPlan>(() => normalizeEssayPlan(read<EssayPlan>(KEY_CURRENT, emptyPlan())));

  useEffect(() => {
    try {
      localStorage.setItem(KEY_CURRENT, JSON.stringify(normalizeEssayPlan({ ...plan, updated_at: Date.now() })));
    } catch { /* noop */ }
  }, [plan]);

  const update = useCallback((patch: Partial<EssayPlan>) => {
    setPlan((p) => normalizeEssayPlan({ ...p, ...patch, updated_at: Date.now() }));
  }, []);

  const reset = useCallback(() => setPlan(emptyPlan()), []);

  return { plan, setPlan, update, reset };
}

export function getCurrentPlan(): EssayPlan {
  return normalizeEssayPlan(read<EssayPlan>(KEY_CURRENT, emptyPlan()));
}

export function setCurrentPlan(plan: EssayPlan) {
  try { localStorage.setItem(KEY_CURRENT, JSON.stringify(normalizeEssayPlan(plan))); } catch {/*noop*/}
}

export function listSavedPlans(): EssayPlan[] {
  return read<EssayPlan[]>(KEY_SAVED, []).map((plan) => normalizeEssayPlan(plan));
}

export function savePlan(plan: EssayPlan): EssayPlan[] {
  const all = listSavedPlans();
  const stamped = normalizeEssayPlan({ ...plan, updated_at: Date.now() });
  const next = [stamped, ...all.filter((p) => p.id !== plan.id)].slice(0, 30);
  try {
    localStorage.setItem(KEY_SAVED, JSON.stringify(next));
  } catch { /* noop */ }
  return next;
}

export function getPlanById(id?: string): EssayPlan | undefined {
  if (!id) return undefined;
  return listSavedPlans().find((p) => p.id === id);
}

/* --------- Timed sessions --------- */
export function saveTimedSession(s: TimedSession) {
  try { localStorage.setItem(KEY_LAST_SESSION, JSON.stringify(s)); } catch {/*noop*/}
}
export function getLastSession(): TimedSession | null {
  return read<TimedSession | null>(KEY_LAST_SESSION, null);
}

/** Toolkit -> Builder bridge: a quote id queued for inclusion. */
const KEY_QUEUED_QUOTE = "c2p.queuedQuoteId.v1";
export function queueQuoteForBuilder(quoteId: string) {
  try { localStorage.setItem(KEY_QUEUED_QUOTE, quoteId); } catch {/*noop*/}
}
export function consumeQueuedQuote(): string | null {
  try {
    const v = localStorage.getItem(KEY_QUEUED_QUOTE);
    if (v) localStorage.removeItem(KEY_QUEUED_QUOTE);
    return v;
  } catch { return null; }
}

/** Toolkit -> Builder bridge: a question family queued for planning. */
const KEY_QUEUED_FAMILY = "c2p.queuedFamily.v1";
export function queueFamilyForBuilder(family: QuestionFamily) {
  try { localStorage.setItem(KEY_QUEUED_FAMILY, family); } catch {/*noop*/}
}
export function consumeQueuedFamily(): QuestionFamily | null {
  try {
    const v = localStorage.getItem(KEY_QUEUED_FAMILY);
    if (v) localStorage.removeItem(KEY_QUEUED_FAMILY);
    return (v as QuestionFamily) || null;
  } catch { return null; }
}
