import { describe, it, expect } from "vitest";
import { essayPlanToInsert, rowToEssayPlan } from "./planCloud";
import type { EssayPlanRow } from "./planCloud";

const basePlan = {
  id: "plan-abc-123",
    updated_at: 1714000000000,
      thesis_level: "strong" as const,
        selected_quote_ids: ["q1", "q2"],
          ao5_enabled: true,
            selected_ao5_ids: ["a1"],
              paragraph_cards: [],
                builder_handoffs: [],
                };

                const userId = "user-xyz";

                describe("essayPlanToInsert", () => {
                  it("maps EssayPlan fields to insert payload", () => {
                      const payload = essayPlanToInsert(basePlan, userId);

                          expect(payload.user_id).toBe(userId);
                              expect(payload.client_plan_id).toBe(basePlan.id);
                                  expect(payload.thesis_level).toBe("strong");
                                      expect(payload.selected_quote_ids).toEqual(["q1", "q2"]);
                                          expect(payload.ao5_enabled).toBe(true);
                                              expect(payload.selected_ao5_ids).toEqual(["a1"]);
                                                  expect(payload.is_current).toBe(false);
                                                      expect(payload.notes).toBeNull();
                                                        });

                                                          it("sets is_current when provided", () => {
                                                              const payload = essayPlanToInsert({ ...basePlan, is_current: true }, userId);
                                                                  expect(payload.is_current).toBe(true);
                                                                    });

                                                                      it("maps optional plan fields to null when absent", () => {
                                                                          const payload = essayPlanToInsert(basePlan, userId);
                                                                              expect(payload.question_id).toBeNull();
                                                                                  expect(payload.family).toBeNull();
                                                                                      expect(payload.route_id).toBeNull();
                                                                                          expect(payload.thesis_id).toBeNull();
                                                                                            });

                                                                                              it("preserves notes when provided", () => {
                                                                                                  const payload = essayPlanToInsert({ ...basePlan, notes: "My notes" }, userId);
                                                                                                      expect(payload.notes).toBe("My notes");
                                                                                                        });
                                                                                                        });
                                                                                                        
                                                                                                        describe("rowToEssayPlan", () => {
                                                                                                          const baseRow: EssayPlanRow = {
                                                                                                              id: "row-uuid-1",
                                                                                                                  client_plan_id: "plan-abc-123",
                                                                                                                      user_id: "user-xyz",
                                                                                                                          created_at: "2024-04-25T00:00:00.000Z",
                                                                                                                              updated_at: "2024-04-25T12:00:00.000Z",
                                                                                                                                  thesis_level: "strong",
                                                                                                                                      selected_quote_ids: ["q1", "q2"],
                                                                                                                                          ao5_enabled: true,
                                                                                                                                              selected_ao5_ids: ["a1"],
                                                                                                                                                  paragraph_cards: [],
                                                                                                                                                      builder_handoffs: [],
                                                                                                                                                          is_current: false,
                                                                                                                                                              question_id: null,
                                                                                                                                                                  family: null,
                                                                                                                                                                      route_id: null,
                                                                                                                                                                          thesis_id: null,
                                                                                                                                                                              notes: null,
                                                                                                                                                                                };
                                                                                                                                                                                
                                                                                                                                                                                  it("maps row fields back to EssayPlan", () => {
                                                                                                                                                                                      const plan = rowToEssayPlan(baseRow);
                                                                                                                                                                                      
                                                                                                                                                                                          expect(plan.id).toBe("plan-abc-123");
                                                                                                                                                                                              expect(plan.thesis_level).toBe("strong");
                                                                                                                                                                                                  expect(plan.selected_quote_ids).toEqual(["q1", "q2"]);
                                                                                                                                                                                                      expect(plan.ao5_enabled).toBe(true);
                                                                                                                                                                                                          expect(plan.selected_ao5_ids).toEqual(["a1"]);
                                                                                                                                                                                                              expect(plan.paragraph_cards).toEqual([]);
                                                                                                                                                                                                                  expect(plan.builder_handoffs).toEqual([]);
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                    
                                                                                                                                                                                                                      it("falls back to row.id when client_plan_id is null", () => {
                                                                                                                                                                                                                          const row = { ...baseRow, client_plan_id: null };
                                                                                                                                                                                                                              const plan = rowToEssayPlan(row);
                                                                                                                                                                                                                                  expect(plan.id).toBe("row-uuid-1");
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                      it("converts updated_at ISO string to numeric timestamp", () => {
                                                                                                                                                                                                                                          const plan = rowToEssayPlan(baseRow);
                                                                                                                                                                                                                                              expect(typeof plan.updated_at).toBe("number");
                                                                                                                                                                                                                                                  expect(plan.updated_at).toBe(new Date("2024-04-25T12:00:00.000Z").getTime());
                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      it("maps null optional fields to undefined on the plan", () => {
                                                                                                                                                                                                                                                          const plan = rowToEssayPlan(baseRow);
                                                                                                                                                                                                                                                              expect(plan.question_id).toBeUndefined();
                                                                                                                                                                                                                                                                  expect(plan.family).toBeUndefined();
                                                                                                                                                                                                                                                                      expect(plan.route_id).toBeUndefined();
                                                                                                                                                                                                                                                                          expect(plan.thesis_id).toBeUndefined();
                                                                                                                                                                                                                                                                              expect(plan.notes).toBeUndefined();
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                  it("round-trips: essayPlanToInsert then rowToEssayPlan preserves core fields", () => {
                                                                                                                                                                                                                                                                                      const payload = essayPlanToInsert(basePlan, userId);
                                                                                                                                                                                                                                                                                          const simulatedRow: EssayPlanRow = {
                                                                                                                                                                                                                                                                                                id: "row-uuid-new",
                                                                                                                                                                                                                                                                                                      user_id: userId,
                                                                                                                                                                                                                                                                                                            client_plan_id: payload.client_plan_id,
                                                                                                                                                                                                                                                                                                                  created_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                        updated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                              thesis_level: payload.thesis_level,
                                                                                                                                                                                                                                                                                                                                    selected_quote_ids: payload.selected_quote_ids,
                                                                                                                                                                                                                                                                                                                                          ao5_enabled: payload.ao5_enabled,
                                                                                                                                                                                                                                                                                                                                                selected_ao5_ids: payload.selected_ao5_ids,
                                                                                                                                                                                                                                                                                                                                                      paragraph_cards: payload.paragraph_cards,
                                                                                                                                                                                                                                                                                                                                                            builder_handoffs: payload.builder_handoffs,
                                                                                                                                                                                                                                                                                                                                                                  is_current: payload.is_current,
                                                                                                                                                                                                                                                                                                                                                                        question_id: payload.question_id,
                                                                                                                                                                                                                                                                                                                                                                              family: payload.family,
                                                                                                                                                                                                                                                                                                                                                                                    route_id: payload.route_id,
                                                                                                                                                                                                                                                                                                                                                                                          thesis_id: payload.thesis_id,
                                                                                                                                                                                                                                                                                                                                                                                                notes: payload.notes,
                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        const plan = rowToEssayPlan(simulatedRow);
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            expect(plan.id).toBe(basePlan.id);
                                                                                                                                                                                                                                                                                                                                                                                                                expect(plan.thesis_level).toBe(basePlan.thesis_level);
                                                                                                                                                                                                                                                                                                                                                                                                                    expect(plan.selected_quote_ids).toEqual(basePlan.selected_quote_ids);
                                                                                                                                                                                                                                                                                                                                                                                                                        expect(plan.ao5_enabled).toBe(basePlan.ao5_enabled);
                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                          });
