export const ABSTRACT_NOMINALIZATIONS = [
  'mechanization',
  'commodification',
  'determinism',
  'domesticity',
  'utilitarianism',
  'capitalism',
  'rationalism',
  'empiricism',
  'objectification',
  'focalisation',
  'subjectivity',
  'unreliability',
  'victimhood',
  'redemption',
  'guilt',
  'restitution',
  'authorial control',
  'class consciousness',
  'social mobility',
  'paternalism',
  'hegemony',
  'repression',
  'alienation',
  'industrialization',
  'sensory overload',
  'metafiction',
  'structural irony',
  'omniscience',
];

export const WEAK_CONNECTIVES = [
  'firstly',
  'secondly',
  'thirdly',
  'in addition',
  'furthermore',
  'then',
  'next',
  'after this',
  'finally',
  'to begin with',
  'first of all',
  'moreover',
  'on top of that',
  'lastly',
];

export const AUTHORIAL_DESIGN_VERBS = [
  'codifies',
  'dissects',
  'spatializes',
  'deconstructs',
  'externalizes',
  'internalizes',
  'subverts',
  'satirizes',
  'reconstructs',
  'delineates',
  'critiques',
  'interrogates',
  'exposes',
  'embodies',
  'orchestrates',
  'dramatizes',
  'shapes',
  'patterns',
  'frames',
  'juxtaposes',
  'synthesizes',
  'constructs',
  'undermines',
];

export const MODAL_VERBS = [
  'might suggest',
  'could possibly',
  'maybe shows',
  'perhaps means',
  'seems to show',
  'possibly reflects',
  'might mean',
  'could indicate',
  'may indicate',
  'likely means',
  'might indicate',
  'perhaps shows',
];

export const AO2_DEVICES = [
  'metaphor',
  'satire',
  'focalisation',
  'focalizer',
  'focalised',
  'omniscience',
  'free indirect',
  'irony',
  'symbol',
  'motif',
  'imagery',
  'diction',
  'allegory',
  'narrator',
  'narrative voice',
  'caricature',
  'zoomorphism',
  'nomenclature',
  'rhetoric',
  'syntax',
  'anaphora',
  'repetition',
  'structural device',
  'focalisation',
  'retrospective',
  'narrative gap',
  'ellipsis',
  'fragmentation',
  'close reading',
];

export const AO3_CONTEXTS = [
  'utilitarian',
  'industrial',
  'victorian',
  'class',
  'capitalism',
  'dunkirk',
  'war',
  'bourgeois',
  'proletariat',
  'laissez-faire',
  '1854',
  '1935',
  '1940',
  'socio-political',
  'patriarchy',
  'education',
  'historical',
  'pressure',
  'society',
  'social control',
  'institutional',
  'reform',
  'interwar',
  '1930s',
];

// Helper dictionaries mapping literary devices and contextual concepts
// for optimized token distance scans.
export const AO_MAPPING_DICTIONARY = {
  AO2: AO2_DEVICES,
  AO3: AO3_CONTEXTS,
};
