/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimedEssayBuilderMockRouteImport } from './routes/timed-essay-builder-mock'
import { Route as ThemeWheelMockRouteImport } from './routes/theme-wheel-mock'
import { Route as QuoteMethodBankMockRouteImport } from './routes/quote-method-bank-mock'
import { Route as DashboardMockRouteImport } from './routes/dashboard-mock'
import { Route as ComparativeMatrixMockRouteImport } from './routes/comparative-matrix-mock'
import { Route as IndexRouteImport } from './routes/index'

const TimedEssayBuilderMockRoute = TimedEssayBuilderMockRouteImport.update({
  id: '/timed-essay-builder-mock',
  path: '/timed-essay-builder-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeWheelMockRoute = ThemeWheelMockRouteImport.update({
  id: '/theme-wheel-mock',
  path: '/theme-wheel-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteMethodBankMockRoute = QuoteMethodBankMockRouteImport.update({
  id: '/quote-method-bank-mock',
  path: '/quote-method-bank-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMockRoute = DashboardMockRouteImport.update({
  id: '/dashboard-mock',
  path: '/dashboard-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeMatrixMockRoute = ComparativeMatrixMockRouteImport.update({
  id: '/comparative-matrix-mock',
  path: '/comparative-matrix-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparative-matrix-mock': typeof ComparativeMatrixMockRoute
  '/dashboard-mock': typeof DashboardMockRoute
  '/quote-method-bank-mock': typeof QuoteMethodBankMockRoute
  '/theme-wheel-mock': typeof ThemeWheelMockRoute
  '/timed-essay-builder-mock': typeof TimedEssayBuilderMockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparative-matrix-mock': typeof ComparativeMatrixMockRoute
  '/dashboard-mock': typeof DashboardMockRoute
  '/quote-method-bank-mock': typeof QuoteMethodBankMockRoute
  '/theme-wheel-mock': typeof ThemeWheelMockRoute
  '/timed-essay-builder-mock': typeof TimedEssayBuilderMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparative-matrix-mock': typeof ComparativeMatrixMockRoute
  '/dashboard-mock': typeof DashboardMockRoute
  '/quote-method-bank-mock': typeof QuoteMethodBankMockRoute
  '/theme-wheel-mock': typeof ThemeWheelMockRoute
  '/timed-essay-builder-mock': typeof TimedEssayBuilderMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparative-matrix-mock'
    | '/dashboard-mock'
    | '/quote-method-bank-mock'
    | '/theme-wheel-mock'
    | '/timed-essay-builder-mock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparative-matrix-mock'
    | '/dashboard-mock'
    | '/quote-method-bank-mock'
    | '/theme-wheel-mock'
    | '/timed-essay-builder-mock'
  id:
    | '__root__'
    | '/'
    | '/comparative-matrix-mock'
    | '/dashboard-mock'
    | '/quote-method-bank-mock'
    | '/theme-wheel-mock'
    | '/timed-essay-builder-mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparativeMatrixMockRoute: typeof ComparativeMatrixMockRoute
  DashboardMockRoute: typeof DashboardMockRoute
  QuoteMethodBankMockRoute: typeof QuoteMethodBankMockRoute
  ThemeWheelMockRoute: typeof ThemeWheelMockRoute
  TimedEssayBuilderMockRoute: typeof TimedEssayBuilderMockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timed-essay-builder-mock': {
      id: '/timed-essay-builder-mock'
      path: '/timed-essay-builder-mock'
      fullPath: '/timed-essay-builder-mock'
      preLoaderRoute: typeof TimedEssayBuilderMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-wheel-mock': {
      id: '/theme-wheel-mock'
      path: '/theme-wheel-mock'
      fullPath: '/theme-wheel-mock'
      preLoaderRoute: typeof ThemeWheelMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-method-bank-mock': {
      id: '/quote-method-bank-mock'
      path: '/quote-method-bank-mock'
      fullPath: '/quote-method-bank-mock'
      preLoaderRoute: typeof QuoteMethodBankMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-mock': {
      id: '/dashboard-mock'
      path: '/dashboard-mock'
      fullPath: '/dashboard-mock'
      preLoaderRoute: typeof DashboardMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative-matrix-mock': {
      id: '/comparative-matrix-mock'
      path: '/comparative-matrix-mock'
      fullPath: '/comparative-matrix-mock'
      preLoaderRoute: typeof ComparativeMatrixMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparativeMatrixMockRoute: ComparativeMatrixMockRoute,
  DashboardMockRoute: DashboardMockRoute,
  QuoteMethodBankMockRoute: QuoteMethodBankMockRoute,
  ThemeWheelMockRoute: ThemeWheelMockRoute,
  TimedEssayBuilderMockRoute: TimedEssayBuilderMockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
