-- Seed Annotated Paper 2 Essay Practice Pack — Hard Times / Atonement
-- Generated from src/data/annotatedEssayPracticePack/index.ts.
-- Content remains marked teacher review required and reviewed=false.

begin;

insert into public.essay_questions (
  id, paper_code, component, exam_board, year, question_text, theme, marks,
  text_pair, pre_1900_text, post_1900_text, ao_requirements, difficulty_level,
  question_family, likely_routes, linked_quote_cluster_ids, linked_paragraph_stem_ids,
  pitfalls, level_5_upgrade_moves, source, content_type, verification_status,
  reviewed, created_at, updated_at
)
values
  ('eq_ht_at_children_roles_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare how the writers present the roles of children in Hard Times and Atonement.', 'childhood', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'top_band', 'childhood', array['children as products of adult systems', 'imagination as moral formation and distortion', 'child testimony and adult responsibility', 'narrative control over damaged childhood']::text[], array['qcl_childhood_fact_fancy', 'qcl_briony_order_testimony']::text[], array['stem_childhood_systems_ao1', 'stem_childhood_method_ao2', 'stem_childhood_context_ao3']::text[], array['Retelling Briony''s plot before establishing a comparative argument.', 'Treating Dickens as simply pro-child and McEwan as simply anti-child.', 'Bolting Victorian education context onto the end of the paragraph.']::text[], array['Use ''role'' conceptually: child as victim, witness, author, moral test and social product.', 'Make every paragraph pivot between formation in Hard Times and misformation in Atonement.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_important_choices_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare how the writers present characters making important choices in Hard Times and Atonement.', 'important choices', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'strong', 'important choices', array['choice under social pressure', 'speech as action', 'choice and later guilt']::text[], array['qcl_louisa_collapse', 'qcl_briony_testimony']::text[], array['stem_choice_pressure_ao1', 'stem_knowledge_guilt_ao4']::text[], array['Listing choices without judging how free they are.']::text[], array['Separate action, agency and consequence within the topic sentence.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_restrictions_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare how the writers present restrictions placed on individuals within society.', 'restriction', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'top_band', 'restriction', array['class restriction', 'gendered restriction', 'narrative restriction']::text[], array['qcl_coketown_system', 'qcl_robbie_class']::text[], array['stem_restriction_systems_ao4', 'stem_class_social_criticism_ao3']::text[], array['Using society as vague background rather than an active pressure.']::text[], array['Name the institution doing the restricting before moving to evidence.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_education_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare the significance of education, formal or informal, in Hard Times and Atonement.', 'education', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'top_band', 'education', array['formal schooling', 'reading and misreading', 'moral education after harm']::text[], array['qcl_fact_schoolroom', 'qcl_briony_library']::text[], array['stem_education_formal_informal_ao2', 'stem_childhood_context_ao3']::text[], array['Assuming education only means school scenes.']::text[], array['Use informal education to compare Briony''s reading habits with Louisa''s emotional deprivation.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_friendship_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare how the writers present friendship in Hard Times and Atonement.', 'friendship', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'secure', 'friendship', array['Sissy''s loyal care', 'Robbie and Cecilia''s intimacy', 'friendship as trust against systems']::text[], array['qcl_sissy_care', 'qcl_robbie_cecilia_letters']::text[], array['stem_friendship_trust_ao1']::text[], array['Letting friendship become a love-only essay.']::text[], array['Define friendship as moral attention, not just affection.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_marriage_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare the presentation of marriage in Hard Times and Atonement.', 'marriage', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'strong', 'marriage', array['marriage as transaction', 'marriage as social cover', 'unmarried intimacy and consequence']::text[], array['qcl_louisa_bounderby', 'qcl_lola_marriage']::text[], array['stem_marriage_transaction_ao3']::text[], array['Forgetting Lola and Paul Marshall as a structural aftershock.']::text[], array['Compare marriage as economic enclosure with marriage as reputational concealment.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_knowledge_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare the effects of knowledge on characters in Hard Times and Atonement.', 'knowledge', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'top_band', 'knowledge', array['facts without wisdom', 'knowledge too late', 'misread knowledge']::text[], array['qcl_fact_vs_wisdom', 'qcl_old_briony_coda']::text[], array['stem_knowledge_guilt_ao4', 'stem_memory_reconstruction_ao2']::text[], array['Equating knowledge with truth.']::text[], array['Distinguish information, interpretation and moral knowledge.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('eq_ht_at_settings_20260524', '9ET0/02', 'Component 2 — Prose', 'Pearson Edexcel', null, 'Compare the significance of settings in Hard Times and Atonement.', 'place', 40, 'Hard Times / Atonement', 'Hard Times', 'Atonement', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'strong', 'place', array['Coketown as social machine', 'Tallis estate as insulated stage', 'Dunkirk as exposed system']::text[], array['qcl_coketown_system', 'qcl_tallis_estate_heat']::text[], array['stem_place_system_stage_ao2']::text[], array['Describing setting without making it do analytical work.']::text[], array['Treat place as an argument about power and perception.']::text[], 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  paper_code = excluded.paper_code,
  component = excluded.component,
  exam_board = excluded.exam_board,
  year = excluded.year,
  question_text = excluded.question_text,
  theme = excluded.theme,
  marks = excluded.marks,
  text_pair = excluded.text_pair,
  pre_1900_text = excluded.pre_1900_text,
  post_1900_text = excluded.post_1900_text,
  ao_requirements = excluded.ao_requirements,
  difficulty_level = excluded.difficulty_level,
  question_family = excluded.question_family,
  likely_routes = excluded.likely_routes,
  linked_quote_cluster_ids = excluded.linked_quote_cluster_ids,
  linked_paragraph_stem_ids = excluded.linked_paragraph_stem_ids,
  pitfalls = excluded.pitfalls,
  level_5_upgrade_moves = excluded.level_5_upgrade_moves,
  source = excluded.source,
  content_type = excluded.content_type,
  verification_status = excluded.verification_status,
  reviewed = excluded.reviewed,
  updated_at = now();

insert into public.annotated_essays (
  id, question_id, title, essay_type, target_band, estimated_mark_range,
  timed_condition_minutes, word_count_band, thesis, full_essay_text,
  examiner_summary, strengths, risks, upgrade_targets, student_realism_note,
  source, content_type, verification_status, reviewed, created_at, updated_at
)
values
  ('essay_children_roles_level5_20260524', 'eq_ht_at_children_roles_20260524', 'Level 5 Timed Model: Roles of Children', 'timed-condition model', 'Level 5', '34-38 / 40 after teacher review', 60, '900-1100', 'Dickens presents childhood as something adult systems deform, while McEwan presents childhood as a point where adult class scripts and narrative habits become dangerously active.', 'Both Dickens and McEwan make children central to their social criticism, but they give childhood almost opposite dramatic functions. In Hard Times, children expose the violence of an adult system that mistakes measurable knowledge for human formation; in Atonement, Briony exposes the danger of a child who has imaginative power before she has moral judgement. The comparison is therefore not simply between innocent and guilty children. Dickens presents childhood as something adults deform, while McEwan presents childhood as a stage where adult structures, especially class and gender, can be misread and then brutally enforced. In both novels, the child becomes a test of society''s ethics: what a culture teaches children to see determines what they later damage.

Dickens establishes this critique through the theatrical harshness of the schoolroom. Gradgrind''s opening demand for "Facts" turns education into command, and the capitalised abstraction makes fact sound less like knowledge than a false religion. The children are addressed collectively, as if individuality is an error to be corrected. Sissy Jupe''s reduction to "girl number twenty" is especially useful because Dickens compresses a whole pedagogy into a label: the child is counted before she is known. This method is satirical but also structural, because the novel''s adult disasters grow from this opening scene. Louisa''s later emotional blankness and Tom''s selfishness are not sudden moral failures; they are the results of a childhood trained to distrust feeling. By contrast, Briony Tallis is not starved of imagination. McEwan''s free indirect style places the reader inside a child''s craving for aesthetic order, especially in the early description of her wish to make the world "just so". Where Dickens uses caricature and repeated imperatives to show adults pressing children into shape, McEwan uses focalisation to show a child pressing the world into story. Both methods make childhood unstable, but Dickens locates the danger in institutional reduction whereas McEwan locates it in interpretive excess.

The writers also differ in how far children understand the social worlds they inhabit. Sissy''s apparent ignorance repeatedly proves morally intelligent because she recognises feeling, loyalty and dependency where Gradgrind''s system sees only utility. Her circus background matters contextually: Dickens uses Sleary''s world of performance and fancy to resist mid-Victorian utilitarian education, especially the belief that facts alone could produce social improvement. Sissy is a child of informal education, and her role is to preserve human sympathy inside Coketown''s industrial logic. Briony, however, has been informally educated by books, country-house manners and class assumptions. Her mistake over Robbie is not only childish confusion; it is a socially authorised misreading. Because Robbie is vulnerable as an educated servant''s son, her confident testimony is believed. McEwan''s interwar setting therefore makes childhood part of a class system that decides whose story sounds plausible. Dickens asks what happens when adults deny children fancy; McEwan asks what happens when a child inherits the wrong social scripts for interpreting evidence.

This contrast becomes sharper when the child takes on the role of witness. In Hard Times, Bitzer is perhaps Gradgrind''s most successful pupil, and that success is morally chilling. His literalism in the later bank episode shows that the system can produce a child who obeys its logic perfectly and yet lacks pity. Dickens structures Bitzer almost as a warning from the first schoolroom to the final crisis: a child educated by fact becomes an adult who can use fact against his teacher. Briony''s witnessing is more formally complex. McEwan makes the reader experience uncertainty through restricted perception and delayed correction, so the child''s statement becomes a narrative event as well as a plot event. The damage comes from language acquiring legal force before understanding catches up. In both novels, children do not merely observe adult society; they reproduce it. Bitzer reproduces utilitarian calculation, while Briony reproduces class prejudice in the grammar of certainty. That sustained comparison is important because it prevents the essay from treating Briony as uniquely monstrous. She is culpable, but her culpability is enabled by the adult world that believes her.

Gender also shapes the role children are allowed to play. Louisa is trained into repression and then exchanged into marriage with Bounderby, so Dickens connects girlhood to economic and patriarchal control. Her childhood has prepared her to consent without understanding the emotional cost of consent. The famous collapse before Gradgrind is therefore not only a daughter''s complaint but an indictment of a father who has confused obedience with education. McEwan''s Briony has a different kind of power: she is a girl whose story controls other people''s lives, yet the novel also shows how Lola''s suffering is absorbed into silence and later social respectability. Childhood in Atonement is therefore split between authorial power and victimhood. Dickens tends to imagine the damaged child as recoverable through sympathy, especially through Sissy''s influence, whereas McEwan is more sceptical: once Briony''s childhood error enters legal and family history, it cannot be undone by later knowledge. The AO4 hinge is that both writers link girlhood to restricted agency, but Dickens emphasises emotional deprivation while McEwan emphasises the dangerous authority of narrative interpretation.

Finally, both endings return to childhood as an ethical measure of the novel''s world. Dickens allows a partial correction: Gradgrind learns too late that his children needed fancy, affection and moral imagination. This is not a complete social revolution, but it does allow the novel to imagine education being revised. McEwan refuses that comfort. Briony''s old-age authorship can stage Robbie and Cecilia''s survival, but it cannot make that survival historically true. Her art has "absolute power" only inside fiction, and this makes childhood error permanently tragic. The Level 5 argument, then, is that children in these novels are not decorative symbols of innocence. They are the places where systems become visible. Dickens shows a society failing children by narrowing their minds; McEwan shows a society failing through the stories it lets a child tell and the stories it refuses to question. Both writers make childhood a moral origin, but only Dickens leaves open the possibility that formation can be repaired.', 'A thesis-led comparative essay with sustained AO4, precise AO2 on satire/focalisation/structure, and AO3 integrated into the argument rather than attached as background.', array['Argument precedes evidence in every paragraph.', 'Comparison is continuous rather than alternating isolated text blocks.', 'Context is precise: utilitarian schooling, industrial Coketown, interwar class credibility and gendered agency.', 'Timed register feels student-achievable: ambitious but not over-polished.']::text[], array['A real exam answer would need exact edition-checked wording for some Atonement anchors.', 'Paragraph four could quote the testimony scene more precisely after text review.']::text[], array['Add one exact short Robbie/Briony testimony phrase after teacher verification.', 'Sharpen the conclusion by naming one final method contrast: Dickensian moral narration versus McEwan''s metafictional coda.']::text[], 'This is a realistic 60-minute high Level 5 model: six controlled paragraphs, selective evidence, and no dependency on lengthy memorised quotations.', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  question_id = excluded.question_id,
  title = excluded.title,
  essay_type = excluded.essay_type,
  target_band = excluded.target_band,
  estimated_mark_range = excluded.estimated_mark_range,
  timed_condition_minutes = excluded.timed_condition_minutes,
  word_count_band = excluded.word_count_band,
  thesis = excluded.thesis,
  full_essay_text = excluded.full_essay_text,
  examiner_summary = excluded.examiner_summary,
  strengths = excluded.strengths,
  risks = excluded.risks,
  upgrade_targets = excluded.upgrade_targets,
  student_realism_note = excluded.student_realism_note,
  source = excluded.source,
  content_type = excluded.content_type,
  verification_status = excluded.verification_status,
  reviewed = excluded.reviewed,
  updated_at = now();

insert into public.essay_paragraphs (
  id, essay_id, paragraph_number, paragraph_function, comparative_focus,
  main_argument, hard_times_focus, atonement_focus, key_methods, key_contexts,
  paragraph_text, ao_coverage, examiner_comment, upgrade_target, created_at, updated_at
)
values
  ('para_children_roles_1', 'essay_children_roles_level5_20260524', 1, 'comparative thesis and route', 'Childhood as social test in both novels', 'Children reveal the moral failures of the societies that form them.', 'Children deformed by factual utilitarian education.', 'Briony as imaginative child shaped by class scripts.', array['conceptual antithesis', 'comparative framing']::text[], array['Victorian utilitarian education', 'interwar class and gender hierarchy']::text[], 'Both Dickens and McEwan make children central to their social criticism, but they give childhood almost opposite dramatic functions. In Hard Times, children expose the violence of an adult system that mistakes measurable knowledge for human formation; in Atonement, Briony exposes the danger of a child who has imaginative power before she has moral judgement. The comparison is therefore not simply between innocent and guilty children. Dickens presents childhood as something adults deform, while McEwan presents childhood as a stage where adult structures, especially class and gender, can be misread and then brutally enforced. In both novels, the child becomes a test of society''s ethics: what a culture teaches children to see determines what they later damage.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'Strong AO1 because it defines ''roles of children'' conceptually before evidence.', 'Could foreshadow the final form contrast more explicitly.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('para_children_roles_2', 'essay_children_roles_level5_20260524', 2, 'schoolroom and focalisation method paragraph', 'Suppressed imagination versus excessive imaginative ordering', 'Dickens and McEwan both make childhood unstable through contrasting methods.', 'Gradgrind''s schoolroom and Sissy''s numerical label.', 'Briony''s desire for aesthetic order.', array['satire', 'capitalised abstraction', 'free indirect discourse', 'focalisation']::text[], array['utilitarian pedagogy', 'country-house literary childhood']::text[], 'Dickens establishes this critique through the theatrical harshness of the schoolroom. Gradgrind''s opening demand for "Facts" turns education into command, and the capitalised abstraction makes fact sound less like knowledge than a false religion. The children are addressed collectively, as if individuality is an error to be corrected. Sissy Jupe''s reduction to "girl number twenty" is especially useful because Dickens compresses a whole pedagogy into a label: the child is counted before she is known. This method is satirical but also structural, because the novel''s adult disasters grow from this opening scene. Louisa''s later emotional blankness and Tom''s selfishness are not sudden moral failures; they are the results of a childhood trained to distrust feeling. By contrast, Briony Tallis is not starved of imagination. McEwan''s free indirect style places the reader inside a child''s craving for aesthetic order, especially in the early description of her wish to make the world "just so". Where Dickens uses caricature and repeated imperatives to show adults pressing children into shape, McEwan uses focalisation to show a child pressing the world into story. Both methods make childhood unstable, but Dickens locates the danger in institutional reduction whereas McEwan locates it in interpretive excess.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'High AO2: method is named and linked to effect, not merely spotted.', 'Use one more precise Briony phrase after verification.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('para_children_roles_3', 'essay_children_roles_level5_20260524', 3, 'context-integrated comparative paragraph', 'Formal and informal education', 'The novels test whether children can read their societies morally.', 'Sissy as morally intelligent because she resists fact-only education.', 'Briony as reader of class-coded evidence.', array['foil', 'social scripting', 'contrast']::text[], array['mid-Victorian education debates', 'interwar class credibility']::text[], 'The writers also differ in how far children understand the social worlds they inhabit. Sissy''s apparent ignorance repeatedly proves morally intelligent because she recognises feeling, loyalty and dependency where Gradgrind''s system sees only utility. Her circus background matters contextually: Dickens uses Sleary''s world of performance and fancy to resist mid-Victorian utilitarian education, especially the belief that facts alone could produce social improvement. Sissy is a child of informal education, and her role is to preserve human sympathy inside Coketown''s industrial logic. Briony, however, has been informally educated by books, country-house manners and class assumptions. Her mistake over Robbie is not only childish confusion; it is a socially authorised misreading. Because Robbie is vulnerable as an educated servant''s son, her confident testimony is believed. McEwan''s interwar setting therefore makes childhood part of a class system that decides whose story sounds plausible. Dickens asks what happens when adults deny children fancy; McEwan asks what happens when a child inherits the wrong social scripts for interpreting evidence.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'AO3 is integrated through how education and class shape perception.', 'Link the word ''informal'' back to the question in the final sentence.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('para_children_roles_4', 'essay_children_roles_level5_20260524', 4, 'witness and structural consequence', 'Children reproducing adult systems', 'Children do not just observe society; they enact its values.', 'Bitzer as Gradgrindian success turned moral failure.', 'Briony''s restricted perception becoming legal testimony.', array['structural foreshadowing', 'restricted perception', 'delayed correction']::text[], array['utilitarian calculation', 'legal/class credibility']::text[], 'This contrast becomes sharper when the child takes on the role of witness. In Hard Times, Bitzer is perhaps Gradgrind''s most successful pupil, and that success is morally chilling. His literalism in the later bank episode shows that the system can produce a child who obeys its logic perfectly and yet lacks pity. Dickens structures Bitzer almost as a warning from the first schoolroom to the final crisis: a child educated by fact becomes an adult who can use fact against his teacher. Briony''s witnessing is more formally complex. McEwan makes the reader experience uncertainty through restricted perception and delayed correction, so the child''s statement becomes a narrative event as well as a plot event. The damage comes from language acquiring legal force before understanding catches up. In both novels, children do not merely observe adult society; they reproduce it. Bitzer reproduces utilitarian calculation, while Briony reproduces class prejudice in the grammar of certainty. That sustained comparison is important because it prevents the essay from treating Briony as uniquely monstrous. She is culpable, but her culpability is enabled by the adult world that believes her.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'Strong AO4 because Bitzer and Briony are compared as products of social logic.', 'Add one sentence on reader response to the delayed revelation.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('para_children_roles_5', 'essay_children_roles_level5_20260524', 5, 'gendered childhood and agency', 'Girlhood as repression, power and silence', 'Girlhood is restricted in both novels, but the restriction takes different forms.', 'Louisa''s repressed childhood and transactional marriage.', 'Briony''s authorial force and Lola''s silencing.', array['collapse scene', 'character contrast', 'narrative authority']::text[], array['Victorian patriarchy', 'interwar respectability and gender']::text[], 'Gender also shapes the role children are allowed to play. Louisa is trained into repression and then exchanged into marriage with Bounderby, so Dickens connects girlhood to economic and patriarchal control. Her childhood has prepared her to consent without understanding the emotional cost of consent. The famous collapse before Gradgrind is therefore not only a daughter''s complaint but an indictment of a father who has confused obedience with education. McEwan''s Briony has a different kind of power: she is a girl whose story controls other people''s lives, yet the novel also shows how Lola''s suffering is absorbed into silence and later social respectability. Childhood in Atonement is therefore split between authorial power and victimhood. Dickens tends to imagine the damaged child as recoverable through sympathy, especially through Sissy''s influence, whereas McEwan is more sceptical: once Briony''s childhood error enters legal and family history, it cannot be undone by later knowledge. The AO4 hinge is that both writers link girlhood to restricted agency, but Dickens emphasises emotional deprivation while McEwan emphasises the dangerous authority of narrative interpretation.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'Excellent conceptual control over gender without drifting from childhood.', 'Avoid over-expanding Lola; keep her as a comparative pressure point.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('para_children_roles_6', 'essay_children_roles_level5_20260524', 6, 'conclusion and judgement', 'Repairable formation versus irreversible narrative harm', 'Childhood is a moral origin in both novels, but only Dickens imagines partial repair.', 'Gradgrind''s late recognition.', 'Briony''s old-age authorship cannot undo childhood error.', array['ending', 'metafictional coda', 'final judgement']::text[], array['Victorian reform logic', 'postmodern ethics of fiction']::text[], 'Finally, both endings return to childhood as an ethical measure of the novel''s world. Dickens allows a partial correction: Gradgrind learns too late that his children needed fancy, affection and moral imagination. This is not a complete social revolution, but it does allow the novel to imagine education being revised. McEwan refuses that comfort. Briony''s old-age authorship can stage Robbie and Cecilia''s survival, but it cannot make that survival historically true. Her art has "absolute power" only inside fiction, and this makes childhood error permanently tragic. The Level 5 argument, then, is that children in these novels are not decorative symbols of innocence. They are the places where systems become visible. Dickens shows a society failing children by narrowing their minds; McEwan shows a society failing through the stories it lets a child tell and the stories it refuses to question. Both writers make childhood a moral origin, but only Dickens leaves open the possibility that formation can be repaired.', array['AO1', 'AO2', 'AO3', 'AO4']::text[], 'The conclusion sharpens rather than repeats the thesis.', 'Name Dickens''s moral narrator as the formal counterpart to McEwan''s coda.', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  essay_id = excluded.essay_id,
  paragraph_number = excluded.paragraph_number,
  paragraph_function = excluded.paragraph_function,
  comparative_focus = excluded.comparative_focus,
  main_argument = excluded.main_argument,
  hard_times_focus = excluded.hard_times_focus,
  atonement_focus = excluded.atonement_focus,
  key_methods = excluded.key_methods,
  key_contexts = excluded.key_contexts,
  paragraph_text = excluded.paragraph_text,
  ao_coverage = excluded.ao_coverage,
  examiner_comment = excluded.examiner_comment,
  upgrade_target = excluded.upgrade_target,
  updated_at = now();

insert into public.paragraph_stems (
  id, stem_text, "function", ao, source_text, text_focus, best_themes,
  level_band, example_use, sort_order, is_active, curation_status,
  theme, question_family, compatible_characters, compatible_quotes,
  method_triggers, context_route, comparison_route, drill_instruction,
  timed_target_minutes, source, content_type, verification_status, reviewed
)
values
  ('stem_childhood_systems_ao1', 'Both novels present childhood as {concept}, but Dickens locates the damage in {adult system}, whereas McEwan locates it in {misreading or narrative habit}.', 'comparison', array['AO1', 'AO4']::text[], 'Comparative', 'Comparative', array['childhood']::text[], 'top_band', 'Fill the placeholders, then add one method term before any quotation.', 5010, true, 'top_band', 'childhood', 'roles of children', array['Louisa Gradgrind', 'Tom Gradgrind', 'Sissy Jupe', 'Briony Tallis']::text[], array['Facts', 'girl number twenty', 'world just so']::text[], array['comparative thesis', 'conceptual contrast']::text[], 'Victorian utilitarian formation versus interwar class-coded childhood.', 'Formation in Hard Times; misformation in Atonement.', 'Fill the placeholders, then add one method term before any quotation.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_childhood_method_ao2', 'Dickens''s use of {method} makes the child seem {effect}, while McEwan''s {method} makes childhood perception feel {effect}; this contrast matters because {judgement}.', 'method_analysis', array['AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['childhood']::text[], 'top_band', 'Write three sentences: method, effect, comparative judgement.', 5020, true, 'top_band', 'childhood', 'method comparison', array['Sissy Jupe', 'Bitzer', 'Briony Tallis']::text[], array['girl number twenty', 'Facts', 'Briony''s testimony anchor']::text[], array['satire', 'capitalisation', 'free indirect discourse', 'restricted focalisation']::text[], 'Link method to educational theory or narrative modernity.', 'External adult pressure versus internal narrative pressure.', 'Write three sentences: method, effect, comparative judgement.', 5, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_childhood_context_ao3', '{Context} is not background here: it explains why {child/character} learns to see {object/person/world} as {mistaken value}.', 'context', array['AO3', 'AO1']::text[], 'Comparative', 'Comparative', array['childhood']::text[], 'strong', 'Make context explain a character''s perception, not just the author''s world.', 5030, true, 'strong', 'childhood', 'context integration', array['Sissy Jupe', 'Louisa Gradgrind', 'Briony Tallis', 'Robbie Turner']::text[], array['Sleary''s people anchor', 'Robbie class anchor']::text[], array['contextual cause', 'interpretive verb']::text[], 'Utilitarian schooling, circus fancy, interwar estate hierarchy.', 'Context should cause a reading choice in both texts.', 'Make context explain a character''s perception, not just the author''s world.', 4, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_choice_pressure_ao1', 'The important choice appears personal, but both writers show it is shaped by {social pressure}: {Hard Times character} is constrained by {pressure}, while {Atonement character} acts through {pressure}.', 'comparison', array['AO1', 'AO4']::text[], 'Comparative', 'Comparative', array['important choices']::text[], 'strong', 'Open with agency, then test how free the choice really is.', 5040, true, 'strong', 'important choices', 'choice and agency', array['Louisa Gradgrind', 'Gradgrind', 'Briony Tallis', 'Cecilia Tallis']::text[], array['Louisa collapse anchor', 'Briony testimony anchor']::text[], array['dialogue', 'structural crisis', 'focalisation']::text[], 'Victorian patriarchy and interwar class credibility.', 'Constrained consent versus confident misrecognition.', 'Open with agency, then test how free the choice really is.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_restriction_systems_ao4', 'Restriction in both novels is most powerful when it looks normal: Dickens makes {restriction} visible through {image/method}, whereas McEwan makes {restriction} operate through {social assumption/narrative gap}.', 'method_analysis', array['AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['restriction']::text[], 'top_band', 'Use one setting detail and one social detail; compare their pressure.', 5050, true, 'top_band', 'restriction', 'society and individual', array['Stephen Blackpool', 'Louisa Gradgrind', 'Robbie Turner', 'Cecilia Tallis']::text[], array['muddle', 'Coketown smoke', 'Robbie class anchor']::text[], array['industrial imagery', 'dialect', 'free indirect discourse', 'silence']::text[], 'Industrial capitalism and interwar English class hierarchy.', 'Visible machinery versus invisible assumption.', 'Use one setting detail and one social detail; compare their pressure.', 7, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_education_formal_informal_ao2', 'Education is formal in {Hard Times scene} but informal in {Atonement scene}; the methods differ, yet both teach characters to {moral or interpretive outcome}.', 'method_analysis', array['AO1', 'AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['education']::text[], 'top_band', 'Avoid saying ''education is important''; specify what each education teaches.', 5060, true, 'top_band', 'education', 'education', array['Gradgrind', 'Sissy Jupe', 'Briony Tallis', 'Cecilia Tallis']::text[], array['Facts', 'girl number twenty', 'Briony''s play anchor']::text[], array['imperative', 'numbering', 'free indirect discourse']::text[], 'Formal utilitarian schooling versus informal literary/class training.', 'Education as formation of perception.', 'Avoid saying ''education is important''; specify what each education teaches.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_friendship_trust_ao1', 'Friendship functions less as simple affection than as {moral function}: in Dickens it {supports/rescues/exposes}, while in McEwan it {resists/is destroyed by/reveals} social suspicion.', 'comparison', array['AO1', 'AO4']::text[], 'Comparative', 'Comparative', array['friendship']::text[], 'secure', 'Define friendship before using character evidence.', 5070, true, 'secure', 'friendship', 'relationships', array['Sissy Jupe', 'Louisa Gradgrind', 'Robbie Turner', 'Cecilia Tallis']::text[], array['Sissy care anchor', 'Robbie Cecilia letter anchor']::text[], array['dialogue', 'letter', 'contrast']::text[], 'Victorian domestic sympathy and interwar reputational risk.', 'Friendship as moral attention versus fragile trust.', 'Define friendship before using character evidence.', 5, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_marriage_transaction_ao3', 'Marriage becomes a social technology in both novels: Dickens presents it as {transaction}, while McEwan presents it as {concealment/status repair}, revealing {contextual judgement}.', 'context', array['AO1', 'AO3', 'AO4']::text[], 'Comparative', 'Comparative', array['marriage']::text[], 'strong', 'Name the social function of marriage in the topic sentence.', 5080, true, 'strong', 'marriage', 'marriage', array['Louisa Gradgrind', 'Bounderby', 'Lola Quincey', 'Paul Marshall']::text[], array['Louisa Bounderby proposal anchor', 'Lola Marshall marriage anchor']::text[], array['structural irony', 'social tableau', 'narrative omission']::text[], 'Victorian marital economics and twentieth-century respectability.', 'Marriage as exchange versus marriage as cover story.', 'Name the social function of marriage in the topic sentence.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_knowledge_guilt_ao4', 'Knowledge arrives too {late/narrowly/confidently}: Dickens shows {character} learning {truth}, but McEwan shows {character} discovering that knowledge cannot undo {harm}.', 'comparison', array['AO1', 'AO4']::text[], 'Comparative', 'Comparative', array['knowledge']::text[], 'top_band', 'Separate knowing, admitting and repairing.', 5090, true, 'top_band', 'knowledge', 'knowledge and guilt', array['Gradgrind', 'Louisa Gradgrind', 'Briony Tallis']::text[], array['Gradgrind late knowledge anchor', 'absolute power']::text[], array['recognition scene', 'metafictional coda', 'retrospection']::text[], 'Victorian reform possibility versus postmodern limits of repair.', 'Late moral knowledge versus irreversible historical harm.', 'Separate knowing, admitting and repairing.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_memory_reconstruction_ao2', 'Memory is not storage but reconstruction: McEwan''s {method} makes the past feel {effect}, while Dickens''s {method} makes remembered childhood operate as {moral pressure}.', 'method_analysis', array['AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['memory']::text[], 'strong', 'Make form carry the argument about memory.', 5100, true, 'strong', 'memory', 'memory', array['Briony Tallis', 'Louisa Gradgrind', 'Gradgrind']::text[], array['Briony coda anchor', 'Louisa childhood anchor']::text[], array['retrospection', 'metafiction', 'collapse scene']::text[], 'Postwar memory ethics and Victorian moral retrospection.', 'Memory as unstable reconstruction versus moral reckoning.', 'Make form carry the argument about memory.', 7, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_place_system_stage_ao2', 'Setting is not a backdrop: {place} acts as {system/stage}, and the writer''s {method} makes individual behaviour appear {effect}.', 'method_analysis', array['AO2', 'AO1']::text[], 'Comparative', 'Comparative', array['place']::text[], 'strong', 'Use setting to explain behaviour, not just atmosphere.', 5110, true, 'strong', 'place', 'settings', array['Coketown', 'Tallis household', 'Robbie Turner']::text[], array['Coketown smoke', 'Tallis heat anchor', 'Dunkirk road anchor']::text[], array['industrial imagery', 'pathetic fallacy', 'spatial symbolism']::text[], 'Industrial urbanisation, country-house hierarchy and wartime dislocation.', 'Place as social machine versus place as interpretive theatre.', 'Use setting to explain behaviour, not just atmosphere.', 5, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_class_social_criticism_ao3', 'The social criticism is sharpest when class controls {voice/belief/mobility}: Dickens exposes this through {method}, while McEwan exposes it through {method}.', 'method_analysis', array['AO2', 'AO3', 'AO4']::text[], 'Comparative', 'Comparative', array['social criticism']::text[], 'top_band', 'Make class do something active in your sentence.', 5120, true, 'top_band', 'social criticism', 'class', array['Stephen Blackpool', 'Bounderby', 'Robbie Turner', 'Briony Tallis']::text[], array['muddle', 'Robbie class anchor']::text[], array['dialect', 'caricature', 'restricted focalisation']::text[], 'Industrial class hierarchy and interwar class credibility.', 'Class as external oppression versus internalised assumption.', 'Make class do something active in your sentence.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_independence_agency_ao1', 'Independence is presented as {possible/impossible/qualified} because {character} can choose {action} but cannot escape {structure}.', 'context', array['AO1', 'AO3']::text[], 'Comparative', 'Comparative', array['independence']::text[], 'strong', 'Test the limits of independence rather than praising it vaguely.', 5130, true, 'strong', 'independence', 'agency', array['Louisa Gradgrind', 'Cecilia Tallis', 'Robbie Turner', 'Sissy Jupe']::text[], array['Louisa collapse anchor', 'Cecilia defiance anchor']::text[], array['dialogue', 'character contrast', 'structural constraint']::text[], 'Gender, class and family authority.', 'Private resistance against public structures.', 'Test the limits of independence rather than praising it vaguely.', 5, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_violence_visible_invisible_ao4', 'Violence is {visible/invisible} in different ways: Dickens makes harm systemic through {industrial image}, whereas McEwan makes harm narrative through {misreading or withheld truth}.', 'method_analysis', array['AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['violence']::text[], 'top_band', 'Compare the form of violence before the example.', 5140, true, 'top_band', 'violence', 'violence', array['Stephen Blackpool', 'Robbie Turner', 'Briony Tallis']::text[], array['Coketown smoke', 'Dunkirk body-image anchor', 'testimony anchor']::text[], array['imagery', 'synecdoche', 'delayed revelation']::text[], 'Industrial violence and wartime/social violence.', 'Material damage versus epistemic damage.', 'Compare the form of violence before the example.', 7, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_changing_relationships_ao1', 'The relationship changes when {knowledge/pressure/desire} enters it; Dickens structures this as {movement}, while McEwan structures it as {rupture or retrospective revision}.', 'method_analysis', array['AO1', 'AO2', 'AO4']::text[], 'Comparative', 'Comparative', array['changing relationships']::text[], 'strong', 'Use a before/after structure without retelling the plot.', 5150, true, 'strong', 'changing relationships', 'relationships', array['Louisa and Gradgrind', 'Cecilia and Robbie', 'Briony and Cecilia']::text[], array['Louisa collapse anchor', 'Cecilia Robbie fountain anchor']::text[], array['scene structure', 'retrospection', 'dialogue']::text[], 'Family authority and class/gender pressures.', 'Reformable relationship versus irreparable rupture.', 'Use a before/after structure without retelling the plot.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false),
  ('stem_difficult_circumstances_ao3', 'Difficult circumstances reveal not only character but system: {Hard Times example} exposes {Victorian pressure}, while {Atonement example} exposes {twentieth-century pressure}.', 'context', array['AO1', 'AO3', 'AO4']::text[], 'Comparative', 'Comparative', array['difficult circumstances']::text[], 'strong', 'Turn circumstance into cause, then into judgement.', 5160, true, 'strong', 'difficult circumstances', 'suffering', array['Stephen Blackpool', 'Louisa Gradgrind', 'Robbie Turner', 'Cecilia Tallis']::text[], array['muddle', 'factory system anchor', 'Dunkirk road anchor']::text[], array['pathos', 'setting', 'free indirect discourse']::text[], 'Industrial work, gendered family structures, war and class.', 'Systemic hardship in both texts, differently embodied.', 'Turn circumstance into cause, then into judgement.', 6, 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false)
on conflict (id) do update set
  stem_text = excluded.stem_text,
  "function" = excluded."function",
  ao = excluded.ao,
  source_text = excluded.source_text,
  text_focus = excluded.text_focus,
  best_themes = excluded.best_themes,
  level_band = excluded.level_band,
  example_use = excluded.example_use,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  curation_status = excluded.curation_status,
  theme = excluded.theme,
  question_family = excluded.question_family,
  compatible_characters = excluded.compatible_characters,
  compatible_quotes = excluded.compatible_quotes,
  method_triggers = excluded.method_triggers,
  context_route = excluded.context_route,
  comparison_route = excluded.comparison_route,
  drill_instruction = excluded.drill_instruction,
  timed_target_minutes = excluded.timed_target_minutes,
  source = excluded.source,
  content_type = excluded.content_type,
  verification_status = excluded.verification_status,
  reviewed = excluded.reviewed,
  updated_at = now();

insert into public.ao_annotations (
  id, essay_id, paragraph_id, annotation_order, text_span, ao_tags,
  explanation, why_it_scores, improvement_note, annotation_type, created_at, updated_at
)
values
  ('ann_child_001', 'essay_children_roles_level5_20260524', 'para_children_roles_1', 1, 'Both Dickens and McEwan make children central to their social criticism, but they give childhood almost opposite dramatic functions.', array['AO1', 'AO4']::text[], 'Opens with a comparative conceptual claim rather than plot.', 'AO1 is controlled and AO4 is immediate.', 'Could name the exact opposition in the same sentence.', 'thesis', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_002', 'essay_children_roles_level5_20260524', 'para_children_roles_1', 2, 'Dickens presents childhood as something adults deform, while McEwan presents childhood as a stage where adult structures, especially class and gender, can be misread and then brutally enforced.', array['AO1', 'AO3', 'AO4']::text[], 'Sets up the essay route and embeds context as an active pressure.', 'It compares both texts and turns class/gender into argument, not background.', 'A concise method pointer could make the thesis even richer.', 'structural link', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_003', 'essay_children_roles_level5_20260524', 'para_children_roles_2', 3, 'Gradgrind''s opening demand for "Facts" turns education into command, and the capitalised abstraction makes fact sound less like knowledge than a false religion.', array['AO2', 'AO3']::text[], 'Analyses diction and typography while linking to utilitarian education.', 'Method is connected to ideological effect.', 'Add a second micro-word if time allows.', 'AO2 method', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_004', 'essay_children_roles_level5_20260524', 'para_children_roles_2', 4, 'Sissy Jupe''s reduction to "girl number twenty" is especially useful because Dickens compresses a whole pedagogy into a label: the child is counted before she is known.', array['AO2', 'AO1']::text[], 'Uses a short quotation for precise method-led analysis.', 'Explains how naming performs depersonalisation.', 'Could link the label to the later contrast with Briony faster.', 'evidence use', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_005', 'essay_children_roles_level5_20260524', 'para_children_roles_2', 5, 'Where Dickens uses caricature and repeated imperatives to show adults pressing children into shape, McEwan uses focalisation to show a child pressing the world into story.', array['AO2', 'AO4']::text[], 'A clean comparative method sentence.', 'The sentence compares form and effect in both texts.', 'Strong enough for Level 5; keep this pattern in later paragraphs.', 'AO4 comparison', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_006', 'essay_children_roles_level5_20260524', 'para_children_roles_3', 6, 'Her circus background matters contextually: Dickens uses Sleary''s world of performance and fancy to resist mid-Victorian utilitarian education, especially the belief that facts alone could produce social improvement.', array['AO3', 'AO2']::text[], 'Context is woven into the reading of Sissy''s function.', 'Avoids bolt-on context because the history explains the character role.', 'Could mention Household Words only if it serves the argument.', 'AO3 context', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_007', 'essay_children_roles_level5_20260524', 'para_children_roles_3', 7, 'Briony''s mistake over Robbie is not only childish confusion; it is a socially authorised misreading.', array['AO1', 'AO3']::text[], 'Conceptual refinement: the argument avoids moral simplification.', 'Shows Level 5 nuance and precise contextual causation.', 'Pair with a verified short quotation in final revision.', 'evaluative comment', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_008', 'essay_children_roles_level5_20260524', 'para_children_roles_4', 8, 'Bitzer reproduces utilitarian calculation, while Briony reproduces class prejudice in the grammar of certainty.', array['AO1', 'AO3', 'AO4']::text[], 'Compact comparison based on social systems and linguistic action.', 'Balances both texts and makes a judgement about causation.', 'Could add an AO2 phrase explaining ''grammar of certainty''.', 'topic sentence', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_009', 'essay_children_roles_level5_20260524', 'para_children_roles_4', 9, 'McEwan makes the reader experience uncertainty through restricted perception and delayed correction, so the child''s statement becomes a narrative event as well as a plot event.', array['AO2', 'AO1']::text[], 'Explains narrative method and its effect on judgement.', 'Method is treated as meaning, not decoration.', 'Excellent sentence to reuse for narrative-authority questions.', 'AO2 method', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_010', 'essay_children_roles_level5_20260524', 'para_children_roles_5', 10, 'The AO4 hinge is that both writers link girlhood to restricted agency, but Dickens emphasises emotional deprivation while McEwan emphasises the dangerous authority of narrative interpretation.', array['AO1', 'AO4']::text[], 'Explicitly names the comparative hinge.', 'Prevents sequential discussion and sharpens conceptual contrast.', 'In the final essay, remove the label ''AO4 hinge'' if it feels too meta.', 'AO4 comparison', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_011', 'essay_children_roles_level5_20260524', 'para_children_roles_6', 11, 'Dickens allows a partial correction: Gradgrind learns too late that his children needed fancy, affection and moral imagination.', array['AO1', 'AO3']::text[], 'Concluding judgement stays precise and acknowledges partial repair.', 'Shows nuance without drifting into a new paragraph.', 'Could add ''reformist'' if contextual vocabulary is needed.', 'conclusion', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('ann_child_012', 'essay_children_roles_level5_20260524', 'para_children_roles_6', 12, 'Both writers make childhood a moral origin, but only Dickens leaves open the possibility that formation can be repaired.', array['AO1', 'AO4']::text[], 'Final comparative judgement sharpens the thesis.', 'A Level 5 conclusion modifies the opening claim rather than repeats it.', 'Add one form contrast if time remains.', 'conclusion', '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  essay_id = excluded.essay_id,
  paragraph_id = excluded.paragraph_id,
  annotation_order = excluded.annotation_order,
  text_span = excluded.text_span,
  ao_tags = excluded.ao_tags,
  explanation = excluded.explanation,
  why_it_scores = excluded.why_it_scores,
  improvement_note = excluded.improvement_note,
  annotation_type = excluded.annotation_type,
  updated_at = now();

insert into public.quote_method_links (
  id, quotation, speaker_or_narrative_location, text, character, method,
  theme, essay_question_id, paragraph_stem_id, ao2_explanation,
  ao4_comparative_partner, quote_type, verification_status, source,
  content_type, reviewed, created_at, updated_at
)
values
  ('qml_facts_childhood', 'Facts', 'Gradgrind''s opening schoolroom speech', 'Hard Times', 'Thomas Gradgrind', 'capitalised abstract noun and imperative pedagogy', 'childhood', 'eq_ht_at_children_roles_20260524', 'stem_childhood_method_ao2', 'Capitalisation makes an abstraction behave like doctrine, reducing education to command.', 'Briony''s desire to order the world into story in Atonement.', 'verified quotation', 'teacher review required', 'ChatGPT session, 24 May 2026', 'annotated essay practice', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('qml_girl_number_twenty', 'girl number twenty', 'Schoolroom naming of Sissy Jupe', 'Hard Times', 'Sissy Jupe', 'numerical depersonalisation', 'education', 'eq_ht_at_children_roles_20260524', 'stem_childhood_method_ao2', 'The label substitutes category and number for identity.', 'Briony''s classifying imagination in Atonement.', 'verified quotation', 'teacher review required', 'ChatGPT session, 24 May 2026', 'annotated essay practice', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('qml_world_just_so', 'world just so', 'Early Briony focalisation', 'Atonement', 'Briony Tallis', 'free indirect discourse and aesthetic ordering', 'childhood', 'eq_ht_at_children_roles_20260524', 'stem_childhood_systems_ao1', 'The phrase makes childish order feel both charming and ominously controlling.', 'Gradgrind''s equally controlling fact-world in Hard Times.', 'quote anchor / paraphrase', 'teacher review required', 'ChatGPT session, 24 May 2026', 'annotated essay practice', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('qml_muddle_restriction', 'muddle', 'Stephen Blackpool''s repeated account of social confusion', 'Hard Times', 'Stephen Blackpool', 'repeated demotic noun', 'restriction', 'eq_ht_at_restrictions_20260524', 'stem_class_social_criticism_ao3', 'The simple repeated word conveys structural injustice without elite vocabulary.', 'Robbie''s constrained credibility in Atonement.', 'verified quotation', 'teacher review required', 'ChatGPT session, 24 May 2026', 'annotated essay practice', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('qml_absolute_power', 'absolute power', 'Briony''s late metafictional reflection', 'Atonement', 'Briony Tallis', 'metafictional theological vocabulary', 'knowledge', 'eq_ht_at_knowledge_20260524', 'stem_knowledge_guilt_ao4', 'The phrase exposes the gap between fictional control and real moral repair.', 'Gradgrind''s late but socially limited recognition.', 'quote anchor / paraphrase', 'teacher review required', 'ChatGPT session, 24 May 2026', 'annotated essay practice', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  quotation = excluded.quotation,
  speaker_or_narrative_location = excluded.speaker_or_narrative_location,
  text = excluded.text,
  character = excluded.character,
  method = excluded.method,
  theme = excluded.theme,
  essay_question_id = excluded.essay_question_id,
  paragraph_stem_id = excluded.paragraph_stem_id,
  ao2_explanation = excluded.ao2_explanation,
  ao4_comparative_partner = excluded.ao4_comparative_partner,
  quote_type = excluded.quote_type,
  verification_status = excluded.verification_status,
  source = excluded.source,
  content_type = excluded.content_type,
  reviewed = excluded.reviewed,
  updated_at = now();

insert into public.misconception_upgrades (
  id, weakness, diagnosis, example_problem_sentence, improved_level_5_version,
  linked_drill_id, source, content_type, verification_status, reviewed,
  created_at, updated_at
)
values
  ('mis_implied_comparison', 'Comparison is implied but not explicit enough', 'The paragraph discusses both novels but does not name the hinge between them.', 'Dickens shows children are badly educated. McEwan also shows Briony making a mistake.', 'Where Dickens makes childhood damage the product of adult education, McEwan makes childhood error the point at which adult class assumptions become active.', 'stem_childhood_systems_ao1', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('mis_bolted_context', 'AO3 is bolted on rather than integrated', 'Context appears as a historical fact after the analysis instead of explaining the character or method.', 'This links to Victorian education, which was strict.', 'Dickens''s strict schoolroom matters because mid-Victorian faith in factual instruction is exactly what turns Sissy from a child into a numbered object.', 'stem_childhood_context_ao3', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('mis_method_no_effect', 'AO2 identifies a method but does not explain effect', 'The sentence names a technique but does not say what it makes the reader think.', 'McEwan uses free indirect discourse for Briony.', 'McEwan''s free indirect discourse traps the reader inside Briony''s confident ordering, so the later error feels like a failure of perception rather than a simple lie.', 'stem_childhood_method_ao2', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('mis_plot_opening', 'Paragraph begins with plot rather than argument', 'The first sentence tells the story instead of answering the question.', 'At the start of Hard Times Gradgrind is in a classroom talking to children.', 'Dickens begins in a classroom because the novel wants childhood to reveal the violence of a society that mistakes instruction for formation.', 'stem_education_formal_informal_ao2', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('mis_sequential_texts', 'Dickens and McEwan are discussed sequentially rather than comparatively', 'The paragraph has a Hard Times half and an Atonement half with no internal bridge.', 'In Hard Times children suffer. In Atonement Briony is a child.', 'Both novels make children agents of social meaning, but Dickens emphasises children suffering under adult systems whereas McEwan emphasises a child reproducing those systems through interpretation.', 'stem_restriction_systems_ao4', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z'),
  ('mis_repeated_conclusion', 'Conclusion repeats the thesis without sharpening it', 'The ending says the same thing again and misses the final judgement.', 'In conclusion, both writers present children as important.', 'Ultimately, childhood matters in both novels because it is where society first writes itself into the individual; Dickens imagines revision, but McEwan leaves the damage historically irreversible.', 'stem_knowledge_guilt_ao4', 'ChatGPT session, 24 May 2026', 'annotated essay practice', 'teacher review required', false, '2026-05-24T00:00:00.000Z', '2026-05-24T00:00:00.000Z')
on conflict (id) do update set
  weakness = excluded.weakness,
  diagnosis = excluded.diagnosis,
  example_problem_sentence = excluded.example_problem_sentence,
  improved_level_5_version = excluded.improved_level_5_version,
  linked_drill_id = excluded.linked_drill_id,
  source = excluded.source,
  content_type = excluded.content_type,
  verification_status = excluded.verification_status,
  reviewed = excluded.reviewed,
  updated_at = now();

commit;
